version: '3'

services:
  backend-server:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app
    ports:
      - '8001:8001'
    depends_on:
      - db
    command: > 
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'admin')\" &&
             python manage.py runserver 0.0.0.0:8001"

  frontend-server:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend:/app
    ports:
      - '80:80'

  db:
    image: postgres:latest
    env_file:
      - Backend/.env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: